### ISSUE TITLE
客户端断线重连

### ISSUE THREAD

**Issue by WiseDiligent** [yuqianglianshou/WebSocket#1]
请问一下，使用客户端的时候，客户端异常断开，支持自动重连吗，代码中，没有看到呢

**Comment by yuqianglianshou** [comment]
代码中并未体现断线重连的，需要添加心跳检测代码，即每隔一定时间向服务端发送一次确认信息，收到回复则正在连接，未收到回复则意味着已经断开链接，判断断开连接了重新走一次开启连接服务端的方法即可。
